Repository 2025-LIKELION-HACKATHON-NIEUNDASEOT/frontend, pull requests merged in 2025-08, with the labels that each got.

#2 Feat: Navigator UI 구현
  src/App.js
  src/assets/.gitkeep
  src/assets/Navigator/home-false.svg
  src/assets/Navigator/home-true.svg
  src/assets/Navigator/my-false.svg
  src/assets/Navigator/my-true.svg
  src/assets/Navigator/news-false.svg
  src/assets/Navigator/news-true.svg
  src/assets/Navigator/noti-false.svg
  src/assets/Navigator/noti-true.svg
  src/components/.gitkeep
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/NavigatorIcons.js
  src/components/Navigator/NavigatorStyle.jsx
  src/components/layout/Main.jsx
  src/styles/GlobalStyle.jsx
Labels: ✨ Feat

#4 Docs: 제목 부분, 내용 부분 Mock Data 파일 생성
  public/data/CardList.json
  public/data/Detail.json
Labels: 📚 Docs

#6 Feat: GoToTop 버튼 UI 및 기능 구현
  src/assets/arrow_upward.svg
  src/components/GoToTop/GoToTop.jsx
  src/components/Navigator/NavigatorStyle.jsx
  src/styles/ButtonCircle.jsx
  src/styles/GlobalStyle.jsx
Labels: ✨ Feat

#10 Feat: useFetch hook 추가, 공문 상세 페이지 및 공유하기 토스트 UI 구현
  public/data/EachDetail.json
  src/assets/Detail/bookmark_false.svg
  src/assets/Detail/bookmark_true.svg
  src/assets/Detail/share.svg
  src/assets/check_circle.svg
  src/components/ShareToast/ShareToast.jsx
  src/components/ShareToast/ShareToastStyle.jsx
  src/hooks/.gitkeep
  src/hooks/useFetch.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/DetailStyle.jsx
Labels: ✨ Feat, 🎨 Design

#12 Design: 본문 상세 페이지 Badge, CardList 컴포넌트로 교체
  public/data/CardList.json
  src/components/Badge/BadgeStyle.js
  src/components/GoToTop/GoToTop.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/DetailStyle.jsx
  src/styles/ButtonCircle.jsx
Labels: 🎨 Design, ✏️ Typo

#13 Feat: Chatbot 페이지 UI 구현
  src/assets/ChatbotInputField/arrow-up-false.svg
  src/assets/ChatbotInputField/arrow-up-true.svg
  src/components/Chatbot/Chatbot.jsx
  src/components/Chatbot/ChatbotStyle.jsx
  src/components/ChatbotInputField/ChatbotInputField.jsx
  src/components/ChatbotInputField/ChatbotInputFieldStyle.jsx
  src/pages/Detail/Detail.jsx
Labels: ✨ Feat, 🎨 Design

#15 Feat: chatbot fetch 로직 분리, chatbot 컴포넌트 애니메이션 추가
  .gitignore
  package-lock.json
  src/components/Chatbot/Chatbot.jsx
  src/components/Chatbot/ChatbotStyle.jsx
  src/components/ChatbotInputField/ChatbotInputField.jsx
  src/components/ChatbotInputField/ChatbotInputFieldStyle.jsx
  src/services/.gitkeep
  src/services/chatbot.js
Labels: ✨ Feat, 🎨 Design

#18 Feat: 마이페이지 UI 일부 구현, 일부 연동, useFetch 수정
  src/App.js
  src/assets/chev-right.svg
  src/components/Badge/Badge.jsx
  src/components/Badge/BadgeStyle.js
  src/components/CardList/CardList.jsx
  src/components/CardList/CardListStyle.js
  src/components/MoreBtn/MoreBtn.jsx
  src/components/MoreBtn/MoreBtnStyle.jsx
  src/hooks/useFetch.jsx
  src/pages/Detail/Detail.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPageStyle.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileStyle.jsx
  src/pages/ScrapedChatbots/ScrapedChatbotStyle.jsx
  src/pages/ScrapedChatbots/ScrapedChatbots.jsx
  src/pages/ScrapedPosts/ScrapedPosts.jsx
  src/pages/ScrapedPosts/ScrapedPostsStyle.jsx
Labels: ✨ Feat, 🎨 Design, 🐛 Fix

#19 Feat: 검색창 ui 구현
  src/App.js
  src/assets/arrow_upward.svg
  src/components/CardList/CardListStyle.js
  src/components/SearchInputField/SearchInputFieldStyle.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.js
  src/pages/Search/Search.jsx
  src/pages/Search/SearchStyle.jsx
Labels: ✨ Feat, 🎨 Design

#21 ✨ Feat: 알림 페이지 UI 구현
  src/App.js
  src/components/CardList/CardList.jsx
  src/components/CardList/CardListStyle.js
  src/components/CategoryBar/CategoryBar.jsx
  src/components/CategoryBar/CategoryBarStyle.jsx
  src/components/FilterButton/FilterButton.jsx
  src/components/FilterButton/FilterButtonStyle.jsx
  src/components/GoToTop/GoToTop.jsx
  src/components/Navigator/NavigatorIcons.js
  src/components/SearchInputField/SearchInputFieldStyle.js
  src/components/layout/Main.jsx
  src/pages/Home/HomeStyle.js
  src/pages/Notification/Notification.jsx
  src/pages/Notification/NotificationStyle.jsx
  src/styles/ButtonCircle.jsx
  src/styles/GlobalStyle.jsx
Labels: ✨ Feat, 🎨 Design

#24 ✨ Feat: 공문 스크랩 페이지 UI 구현
  src/assets/Back Icon.svg
  src/pages/ScrapedPosts/ScrapedPosts.jsx
  src/pages/ScrapedPosts/ScrapedPostsStyle.js
  src/pages/Search/Search.jsx
  src/pages/Search/SearchStyle.js
Labels: ✨ Feat, 🎨 Design

#25 Feat: 챗봇 스크랩 페이지 UI 구현
  src/components/ChatbotBox/ChatbotBox.jsx
  src/components/ChatbotBox/ChatbotBoxStyle.js
  src/components/GoToTop/GoToTop.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/ScrapedChatbots/ScrapedChatbotStyle.js
  src/pages/ScrapedChatbots/ScrapedChatbots.jsx
  src/pages/ScrapedPosts/ScrapedPosts.jsx
  src/pages/ScrapedPosts/ScrapedPostsStyle.js
  src/services/filter.js
  src/services/smallFilter.js
Labels: ✨ Feat, 🎨 Design, 🐛 Fix, ✏️ Typo

#26 ✨ Feat: 소식 페이지 UI 구현
  src/App.js
  src/components/Navigator/NavigatorIcons.js
  src/pages/News/News.jsx
  src/pages/News/NewsStyle.js
  src/pages/Notification/Notification.jsx
  src/pages/Notification/NotificationEmpty.jsx
  src/pages/Notification/NotificationEmptyStyle.js
Labels: 🎨 Design

#27 Feat: 정보수정 페이지, 지역 선택 불가 토스트 UI 구현
  src/assets/Profile/add.svg
  src/assets/Profile/close_small.svg
  src/assets/close_circle.svg
  src/components/DisableToast/DisableToast.jsx
  src/components/DisableToast/DisableToastStyle.js
  src/components/SearchInputField/SearchInputField.jsx
  src/components/SearchInputField/SearchInputFieldStyle.js
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileStyle.js
Labels: 🍱 Assets, ✨ Feat, 🎨 Design, 🐛 Fix

#31 Feat: 홈 화면 일부 연동, 시안에 맞게 UI 변경
  src/assets/homeCharacter.png
  src/assets/homeIcon.svg
  src/components/Badge/BadgeStyle.js
  src/components/Header/Header.jsx
  src/components/Header/HeaderStyle.js
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.js
  src/pages/MyPage/MyPageStyle.js
Labels: ✨ Feat, 🎨 Design

#34 Feat: 소식 페이지 ui 구현 및 기능 추가
  src/assets/noti_img.png
  src/components/Badge/Badge.jsx
  src/components/Badge/BadgeStyle.js
  src/components/CardList/CardList.jsx
  src/components/CardList/CardListStyle.js
  src/components/CategoryBar/CategoryBarStyle.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
  src/components/SearchInputField/SearchInputFieldStyle.jsx
  src/pages/Home/Home.jsx
  src/pages/News/News.jsx
  src/pages/News/NewsStyle.js
  src/pages/Notification/NotificationEmptyStyle.js
  src/pages/Search/SearchStyle.jsx
Labels: ✨ Feat, 🎨 Design

#39 Feat: 프로필 수정 기능 구현
  src/components/Chatbot/Chatbot.jsx
  src/components/ChatbotBox/ChatbotBoxStyle.js
  src/components/SearchInputField/SearchInputField.jsx
  src/components/SearchInputField/SearchInputFieldStyle.jsx
  src/constants/maps.js
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileStyle.js
  src/services/profileService.js
Labels: ♻️ Refactor, ✨ Feat, 🎨 Design, 🐛 Fix

#40 ✨ Feat: 상세 페이지 수정 사항 반영
  src/pages/Detail/Detail.jsx
Labels: ✨ Feat

#41 feat : 알림 페이지 api 연동 및 소식 페이지 오류 수정
  src/components/Filter/Filter.jsx
  src/components/Navigator/NavigatorStyle.js
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.js
  src/pages/News/News.jsx
  src/pages/News/NewsStyle.js
  src/pages/Notification/Notification.jsx
  src/pages/Notification/NotificationEmptyStyle.js
Labels: ✨ Feat, 🎨 Design, 🐛 Fix

#43 Feat: 더미이미지 추가, 필터링 로직 구현
  src/assets/dummyImages/announcement.png
  src/assets/dummyImages/notice.png
  src/assets/dummyImages/participation.png
  src/assets/dummyImages/report.png
  src/components/CardList/CardList.jsx
  src/components/CardList/CardListStyle.js
  src/components/Filter/Filter.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
  src/constants/dummyImages.js
  src/constants/maps.js
  src/hooks/useFetch.js
  src/pages/Detail/Detail.jsx
  src/pages/Home/Home.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPageStyle.js
  src/pages/News/News.jsx
  src/pages/News/NewsStyle.js
  src/pages/Notification/Notification.jsx
  src/pages/Profile/Profile.jsx
  src/pages/ScrapedChatbots/ScrapedChatbots.jsx
  src/pages/ScrapedPosts/ScrapedPosts.jsx
Labels: ✨ Feat, 🎨 Design, 🐛 Fix

#44 Fix: 알림 탭 무한 렌더 오류 수정
  src/pages/Notification/Notification.jsx
Labels: 🐛 Fix

#49 Fix: 배포 후 수정사항 반영
  package-lock.json
  public/favicon.svg
  public/favicons/apple-touch-icon.png
  public/favicons/favicon-96x96.png
  public/favicons/favicon.ico
  public/favicons/favicon.svg
  public/favicons/web-app-manifest-192x192.png
  public/favicons/web-app-manifest-512x512.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/assets/Character.png
  src/assets/dummyImages/announcement.png
  src/assets/dummyImages/notice.png
  src/assets/dummyImages/participation.png
  src/assets/dummyImages/report.png
  src/assets/homeCharacter.png
  src/assets/nochatbot.png
  src/assets/noti_img.png
  src/components/Badge/BadgeStyle.js
  src/components/CardList/CardList.jsx
  src/components/CardList/CardListStyle.js
  src/components/CategoryBar/CategoryBar.jsx
  src/components/Chatbot/Chatbot.jsx
  src/components/Chatbot/ChatbotStyle.js
  src/components/ChatbotBox/ChatbotBox.jsx
  src/components/Empty/Empty.jsx
  src/components/Filter/Filter.jsx
  src/components/PostCard/PostCardStyle.js
  src/components/PushBtn/PushBtn.jsx
  src/index.js
  src/pages/Detail/Detail.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPageStyle.js
  src/pages/News/News.jsx
  src/pages/News/NewsStyle.js
  src/pages/Notification/Notification.jsx
  src/pages/Notification/NotificationEmptyStyle.js
  src/pages/ScrapedChatbots/ScrapedChatbots.jsx
  src/pages/ScrapedPosts/ScrapedPosts.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchStyle.js
  src/pages/Search/SearchStyle.jsx
  src/services/chatbotService.js
  src/services/scrapService.js
  src/styles/GlobalStyle.jsx
  src/utils/makeBadges.js
  src/utils/scrapChatbotEvent.js
  src/utils/scrapChatbotKey.js
Labels: 🍱 Assets, ✨ Feat, 🎨 Design, 🐛 Fix

#50 🔧 Chore: 푸시 알림 세팅 변경
  src/components/PushBtn/PushBtn.jsx
  src/fcm.js
  src/index.js
  src/service-worker.js
Labels: 🔧 Chore

#52 Fix: 디버깅 코드 추가
  src/components/PushBtn/PushBtn.jsx
  src/fcm.js
Labels: 🐛 Fix

#59 Fix/design details
  src/components/CardList/CardListStyle.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/DetailStyle.js
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.js
  src/pages/MyPage/MyPageStyle.js
  src/pages/Search/Search.jsx
  src/service-worker.js
Labels: 🎨 Design, 🐛 Fix
